Simple work on mnist data set to show good coding and comments along with knowledge of neural networks

In [2]:
# list imports first
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras import utils
from sklearn.model_selection import train_test_split

In [3]:
# pulling in and checking data
train = pd.read_csv('./train.csv')
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
#examining the data
train.shape

(42000, 785)

In [5]:
# spliting the data into X and y for the train and test split
X = train.drop('label', axis=1).values
y = train['label']

In [6]:
#sample of single image
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 188, 255,  94,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 191, 250, 253,  93,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [7]:
#scaling X data to be values between 0 and 1, then making the y categorical so that it is values of 0 or 1
X = X/255
y = utils.to_categorical(y)

In [8]:
#checking the x and y values to make sure they are correctly scaled
X[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [10]:
y[0:5]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [11]:
#setting up the train test split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

In [12]:
# reshaping the images for the neural network
# code help https://www.datacamp.com/community/tutorials/cnn-tensorflow-python
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

In [13]:
X_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [14]:
X_train.shape

(31500, 28, 28, 1)

In [15]:
# running a neural network on the training and testing data, changing parameters to try to improve result

cnn_model = Sequential()


cnn_model.add(Conv2D(filters=8,            
                     kernel_size=(3, 3),       
                     activation='relu',     
                     input_shape=(28,28,1))) 

cnn_model.add(MaxPooling2D(pool_size=(2, 2)))

cnn_model.add(Conv2D(16,
                     kernel_size = (3, 3),
                     activation='relu'))

cnn_model.add(MaxPooling2D(pool_size=(2, 2)))

cnn_model.add(Flatten())

cnn_model.add(Dense(128, activation='relu'))


cnn_model.add(Dropout(0.2))

cnn_model.add(Dense(64, activation='relu'))

cnn_model.add(Dropout(0.2))

cnn_model.add(Dense(32, activation='relu'))

cnn_model.add(Dropout(0.2))

cnn_model.add(Dense(10, activation='softmax'))

cnn_model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

history = cnn_model.fit(X_train,
                        y_train,
                        batch_size=256,
                        validation_data=(X_test, y_test),
                        epochs=50,
                        verbose=1)

Epoch 1/50
124/124 [==============================] - 4s 30ms/step - loss: 1.1175 - accuracy: 0.6204 - val_loss: 0.2701 - val_accuracy: 0.9178
Epoch 2/50
124/124 [==============================] - 4s 30ms/step - loss: 0.3066 - accuracy: 0.9117 - val_loss: 0.1341 - val_accuracy: 0.9597
Epoch 3/50
124/124 [==============================] - 4s 32ms/step - loss: 0.1917 - accuracy: 0.9456 - val_loss: 0.1005 - val_accuracy: 0.9699
Epoch 4/50
124/124 [==============================] - 4s 32ms/step - loss: 0.1492 - accuracy: 0.9580 - val_loss: 0.0844 - val_accuracy: 0.9740
Epoch 5/50
124/124 [==============================] - 4s 31ms/step - loss: 0.1200 - accuracy: 0.9670 - val_loss: 0.0705 - val_accuracy: 0.9782
Epoch 6/50
124/124 [==============================] - 4s 32ms/step - loss: 0.1072 - accuracy: 0.9712 - val_loss: 0.0644 - val_accuracy: 0.9802
Epoch 7/50
124/124 [==============================] - 4s 32ms/step - loss: 0.0903 - accuracy: 0.9758 - val_loss: 0.0573 - val_accuracy: 0.9824

In [16]:
#adding in the kaggel test data
test = pd.read_csv('./test.csv')

In [17]:
#checking the test data
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [18]:
#reshaping the test data to fit the model
test = test.values.reshape(-1, 28, 28, 1)

In [23]:
#creating the prediction from the data
preds = cnn_model.predict_classes(test)

In [24]:
preds

array([2, 0, 9, ..., 3, 9, 2])

In [25]:
# turning the predictions into a kaggle submission
test_pred_df = pd.DataFrame({    
    'ImageId': range(1,test.shape[0] + 1),
    'Label': preds
})
test_pred_df.to_csv('preds.csv', index=False)